Adds documentation to build script

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,35 +1,56 @@
 #!/usr/bin/env zsh
 
+## region ############################################## Variables
+
+# Static Variables
 myName="displays-cli"
-myPath="${0:a:h}"
-projPath=$(/usr/bin/dirname "$myPath")
-distPath="${projPath}/dist"
-[ ! -d "$distPath" ] && mkdir -p "$distPath"
-buildPath="${distPath}/build"
-srcPath="${projPath}/src"
-srcFile="${srcPath}/${myName}.sh"
-destFile="${distPath}/${myName}"
-projFile="${srcPath}/${myName}.pkgproj"
+errText=""
+
+# Git Derived
 xGit=$(which git)
 diff=$($xGit diff-index HEAD --)
 oVer=$($xGit describe --abbrev=0 2> /dev/null | /usr/bin/sed 's/^v//')
 [ -z "$oVer" ] && oVer="1.0.0"
 nVer="$oVer"
 
+# Path Variables
+myPath="${0:a:h}"
+projPath=$(/usr/bin/dirname "$myPath")
+distPath="${projPath}/dist"
+buildPath="${distPath}/build"
+srcPath="${projPath}/src"
+srcFile="${srcPath}/${myName}.sh"
+destFile="${distPath}/${myName}"
+projFile="${srcPath}/${myName}.pkgproj"
+[ ! -d "distPath" ] && /bin/mkdir -p "$distPath"
+
+## endregion ################################### End Variables
+
 ## region ###################################### Version Functions
 
+# @description Extracts the major component of a version number.
+# @arg $1 string Version
+# @stdout string Major Component
 version::major() {
   echo "$1" | /usr/bin/awk -F'.' '{ print $1 }'
 }
 
+# @description Extracts the minor component of a version number.
+# @arg $1 string Version
+# @stdout string Minor Component
 version::minor() {
   echo "$1" | /usr/bin/awk -F'.' '{ print $2 }'
 }
 
+# @description Extracts the revision component of a version number.
+# @arg $1 string Version
+# @stdout string Minor Component
 version::revision() {
   echo "$1" | /usr/bin/awk -F'.' '{ print $3 }'
 }
 
+# @description Increments a the version number
+# @noargs
 version::increment() {
   local oMaj oMin oRev
   local nMaj nMin nRev nBuild
@@ -81,27 +102,38 @@ version::increment() {
 
 ## region ###################################### Packages Build
 
+# @description Prepares the main script for distribution.
+# @noargs
 function build::script() {
   /bin/cp "$srcFile" "$destFile"
   /usr/bin/sed -i '' "s/###version###/$nVer/" "${destFile}"
   return 0
 }
 
+# @description Builds the distribution package using Packages, then renames the output with the version number.
+# @noargs
+# @exitcode 0 Success
+# @exitcode 1 Failure
 function build::package() {
-  local retval
+  local retval logFile
 
-  /usr/local/bin/packagesbuild --project "$projFile" --build-folder "$buildPath" --package-version "$nVer" >/dev/null 2>&1
+  logFile=$(/usr/bin/mktemp)
+  /usr/local/bin/packagesbuild --project "$projFile" --build-folder "$buildPath" --package-version "$nVer" >"$logFile" 2>&1
   retval=$?
   if [ "0" -eq "$retval" ]; then
     mv "${buildPath}/${myName}.pkg" "${buildPath}/${myName}-${nVer}.pkg"
+    rm "$logFile"
     return 0
   else
+    errText=$(cat "$logFile")
+    rm "$logFile"
     return 1
   fi
 }
 
 ## endregion ################################### Packages Build
 
+## region ###################################### Input Handling
 
 isMajor=false
 isMinor=false
@@ -116,7 +148,13 @@ while [ "$1" != "" ]; do
   shift # move to next kv pair
 done
 
-! version::increment && echo "ERROR Incrementing Version" && exit 1
+## endregion ################################### Packages Build
+
+## region ###################################### Main Code
+
+! version::increment && echo "Error while Incrementing Version" && exit 1
 ! build::script && echo "ERROR Building Script" && exit 1
-! build::package && echo "ERROR Building Package" && exit 1
+! build::package && echo "ERROR Building Package:" && echo "$errText" && exit 1
 exit 0
+
+## endregion ################################### End Main Code
